### ISSUE TITLE
Cannot install from source b/c the package depends on itself.

### ISSUE THREAD

**Issue by ocefpaf** [geopython/geolinks#10]
The wheel works fine but installing from source no longer works b/c the package imports itself at build time to [check the version](https://github.com/geopython/geolinks/blob/d7cef2fc06d8ae9c026b0877d107b4ff72fba78a/setup.py#L35).

```
> pip install geolinks --no-binary :all:
```

```
Collecting geolinks
  Downloading geolinks-0.2.1.tar.gz (4.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/filipe/micromamba/envs/TEST/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/filipe/micromamba/envs/TEST/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/filipe/micromamba/envs/TEST/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rnbj2uuf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rnbj2uuf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-rnbj2uuf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 35, in <module>
      ModuleNotFoundError: No module named 'geolinks'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I can send a PR to change the code that reads the version and use setuptools_scm to get it from tags if the developers here are OK with it. Or we can use the [existing function](https://github.com/geopython/geolinks/blob/d7cef2fc06d8ae9c026b0877d107b4ff72fba78a/setup.py#L61) to read the version from the `__init__.py` file that is not used at the moment.

**Comment by tomkralidis** [comment]
Thanks for the report.  Fixed in #15 (0.2.2 has now been released to PyPI).
